[project]
name = "uefi_support"
version = "0.9"
authors = [{ name = "Michael Duggan", email = "mwd@cert.org"}]
description = "A package for decompressing file formats found in UEFI distributions"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
